### ISSUE TITLE
Makefile写法有问题导致DEPENDS:=+netdata无效

### ISSUE THREAD

**Issue by kiddin9** [sirpdboy/luci-app-netdata#1]
要么用luci的写法 去掉package相关的东西, 把web文件夹放到 /usr/share/netdata/web  luci.mk会自动完成install
要么用package的写法,去掉luci.mk,行尾加上 $(eval $(call BuildPackage,$(PKG_NAME))), 并在install中通过po2lmo 安装语言包

**Comment by loso3000** [comment]
之前是可以，现在不行了，换了一种方法 。可以正常汉化了。
