### ISSUE TITLE
发现启动不了的原因

### ISSUE THREAD

**Issue by mitsukileung** [sirpdboy/luci-app-netdata#13]
/etc/init.d/netdata 文件只有 rw-rw-r-- 权限，手动改成 rwxrwxr-x 后正常启动。
大佬能不能在编译的时候把这个文件加上权限？

**Comment by mitsukileung** [comment]
把 root/etc/uci-defaults/40_luci-app-netdata 里的
[ -f /usr/share/netdata/webcn/netdata.init ] && mv -f /usr/share/netdata/webcn/netdata.init /etc/init.d/netdata
改成
[ -f /usr/share/netdata/webcn/netdata.init ] && mv -f /usr/share/netdata/webcn/netdata.init /etc/init.d/netdata && chmod +x /etc/init.d/netdata

不知是否可行，有大佬知道吗？

**Comment by sirpdboy** [comment]
正常 是编译的netdate依赖就会加上 权限 ，不过，按你的这里加一个也可以更保险 。
