### ISSUE TITLE
缺少jquery-2.2.4.min.js

### ISSUE THREAD

**Issue by ZenQy** [sirpdboy/luci-app-netdata#7]
请添加，否则加载失败，报错

**Comment by mysteryman2045** [comment]
ERROR 101: Cannot load jQuery: http://192.168.1.133:19999/lib/jquery-2.2.4.min.js
同样的问题，应该是，前边的“jQuery” 大写了Q，后边的“jquery-2.2.4.min.js”小写了q。
一个月前编译LEDE还没这个问题。时隔一个月，昨天编译就遇到了这个问题。

**Comment by saoba1982** [comment]
> ERROR 101: Cannot load jQuery: http://192.168.1.133:19999/lib/jquery-2.2.4.min.js 同样的问题，应该是，前边的“jQuery”大写了Q，后边的“jquery-2.2 .4.min.js”小写了q。 一个月前编译了这个问题。当一个月之前，昨天编译就遇到了这个问题。

你们如何解决的？

**Comment by wyavzz** [comment]
同问题

**Comment by hnyyghk** [comment]
应该是netdata版本升级到了1.33.1导致的
回滚到1.30.1即可

**Comment by sirpdboy** [comment]
已经升级1.33.1 了。编译的话，需要替换源码中原来的luci-app-netdata文件。
